main_app/models.py
from flask import current_app
from main_app import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)

    def __repr__(self):
        return "User({})".format(self.email)

main_app/applications/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, DateField, RadioField
from wtforms.validators import DataRequired, ValidationError

class PreConcertForm(FlaskForm):
    series_name = StringField('Name of series (used to name output)',
        validators=[DataRequired()])
    concert_date = DateField('Date of Concert (m/d/yyyy) example: 9/15/2020',
        validators=[DataRequired()], format='%m/%d/%Y')
    concert_type = RadioField('Concert type',
        choices=[('clx', 'classics'), ('pop', 'pops')])
    this_fy_toDate = FileField('This FY to date: Updated ticket report for the \
        given series',
        validators=[FileAllowed(['csv'])])
    last_year = FileField('Last FY: Updated ticket report for the \
        given series',
        validators=[FileAllowed(['csv'])])
    two_years_back = FileField('Two years back FY: Updated ticket report for \
        the given series',
        validators=[FileAllowed(['csv'])])
    three_years_back = FileField('Three years back FY: Updated ticket report\
        for the given series',
        validators=[FileAllowed(['csv'])])
    customer_info = FileField('Customer Info - (User Defined Format from a \
        List - report in Tessitura)',
        validators=[FileAllowed(['csv'])])
    donor_info = FileField('Donor Info - from the enhanced activity fund report \
        (pull 5 years of data from fiscal years)',
        validators=[FileAllowed(['csv'])])
    submit = SubmitField('Generate')

    def validate_concert_type(self, concert_type):
        if concert_type.data == "None":
            raise ValidationError('Please make a selection')

main_app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo
from main_app.models import User


class RegistrationForm(FlaskForm):

    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(),
                                                EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken')

        email_domain = email.data.split("@",1)[1]
        passing_domain = "pacificsymphony.org"

        if email_domain != passing_domain:
            raise ValidationError('That is not a Pacific Symphony email')


class LoginForm(FlaskForm):

    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

main_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from main_app.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    from main_app.main.routes import main
    from main_app.errors.handlers import errors
    from main_app.users.routes import users
    from main_app.applications.routes import applications
    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(users)
    app.register_blueprint(applications)

    return app

main_app/applications/routes.py
from flask import Blueprint, render_template, flash, send_file
from flask_login import login_required
from main_app.applications.forms import PreConcertForm
from main_app.applications.util.preconcert import pre_concert_fun


applications = Blueprint('applications', __name__)


@applications.route("/preconcert", methods=["GET", "POST"])
@login_required
def preconcert():
    form = PreConcertForm()
    if form.validate_on_submit():
        name = form.series_name.data
        concert_dt = form.concert_date.data
        concert_type = form.concert_type.data
        tix1 = form.this_fy_toDate.data
        tix2 = form.last_year.data
        tix3 = form.two_years_back.data
        tix4 = form.three_years_back.data
        customer = form.customer_info.data
        donor = form.donor_info.data
        send_to_user = pre_concert_fun(name,
                                        concert_dt,
                                        concert_type,
                                        tix1,
                                        tix2,
                                        tix3,
                                        tix4,
                                        customer,
                                        donor)
        # Send file
        return send_to_user
    return render_template('preconcert.html', title='Pre Concert', form=form)

main_app/main/routes.py
from flask import Blueprint, render_template


main = Blueprint('main', __name__)


@main.route("/")
def home():
    return render_template('home.html')

main_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main_app import db, bcrypt
from main_app.models import User
from main_app.users.forms import RegistrationForm, LoginForm


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated: # If user is logged in, redirect
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit(): # For valid post request
        hashed_password = bcrypt.generate_password_hash(form.password.data)\
                                .decode('utf-8')
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('You have been registered, now you can log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # if user is redirected to login page,
            # we can access the parameter of the page that they came from
            # and direct them back to the page they were trying to access
            # before logging in.
            next_page = request.args.get('next')
            flash('You are logged in', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Check email or password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

main_app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1 class="border-bottom">PS Applications</h1>
        <a href="{{ url_for('applications.preconcert') }}">Pre-Concert</a>
    </div>
{% endblock content %}

main_app/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">

        {% if title %}
            <title>PS Application - {{ title }}</title>
        {% else %}
            <title>PS Application</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">PS Apps</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>
        <main role="main" class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </main>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    </body>
</html>

main_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="mb-4">
                <legend class="border-bottom">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="">
                <a href="#">Forgot Password?</a>
                <span> | </span>
                <a href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </div>
{% endblock content %}

main_app/templates/preconcert.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="mb-4">
                <legend class="border-bottom">Pre Concert Inputs</legend>
                <div class="form-group">
                    {{ form.series_name.label(class="form-control-label") }}

                    {% if form.series_name.errors %}
                        {{ form.series_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.series_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.series_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.concert_date.label(class="form-control-label") }}

                    {% if form.concert_date.errors %}
                        {{ form.concert_date(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.concert_date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.concert_date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.concert_type.label(class="form-control-label") }}
                    <br>

                    {% if form.concert_type.errors %}
                        {% for subfield in form.concert_type %}
                        <tr>
                            <td>{{ subfield }}</td>
                            <td>{{ subfield.label }}</td>
                        </tr>
                        {% endfor %}
                        <p class="badge badge-danger">{{ form.concert_type.errors[1] }}</p>
                    {% else %}
                        {% for subfield in form.concert_type %}
                        <tr>
                            <td>{{ subfield }}</td>
                            <td>{{ subfield.label }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </div>
                <br>
                <div class="form-group border rounded p-3">
                    <h5>
                        Ticketing: CSV Files for last 4 years of data for given series
                    </h5>

                    <hr>

                    {{ form.this_fy_toDate.label(class="form-control-label") }}

                    {{ form.this_fy_toDate(class="form-control-file") }}
                    {% if form.this_fy_toDate.errors %}
                        {% for error in form.this_fy_toDate.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}

                    <hr>

                    {{ form.last_year.label(class="form-control-label") }}

                    {{ form.last_year(class="form-control-file") }}
                    {% if form.last_year.errors %}
                        {% for error in form.last_year.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}

                    <hr>

                    {{ form.two_years_back.label(class="form-control-label") }}

                    {{ form.two_years_back(class="form-control-file") }}
                    {% if form.two_years_back.errors %}
                        {% for error in form.two_years_back.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}

                    <hr>

                    {{ form.three_years_back.label(class="form-control-label") }}

                    {{ form.three_years_back(class="form-control-file") }}
                    {% if form.three_years_back.errors %}
                        {% for error in form.three_years_back.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}


                </div>
                <br>
                <div class="form-group border rounded p-3">
                    <h5>
                        Customer: CSV File from 'User Defined Format from List' report in Tessitura
                    </h5>

                    <hr>

                    {{ form.customer_info.label(class="form-control-label") }}

                    {{ form.customer_info(class="form-control-file") }}
                    {% if form.customer_info.errors %}
                        {% for error in form.customer_info.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}

                </div>
                <br>
                <div class="form-group border rounded p-3">
                    <h5>
                        Donor: CSV File from 'enhanced_activity_fund' report in Tessitura
                    </h5>

                    <hr>

                    {{ form.donor_info.label(class="form-control-label") }}

                    {{ form.donor_info(class="form-control-file") }}
                    {% if form.donor_info.errors %}
                        {% for error in form.donor_info.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}

                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

main_app/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="mb-4">
            <legend class="border-bottom">Register</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}

                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}

                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="">
            <a href="{{ url_for('users.login') }}">Log In</a>
        </small>
    </form>
</div>
{% endblock content %}